Algoritmo "questao4"

Var

x1,x2,x3,y1,y2,y3,d: real

Inicio

escreva ("Qual o valor de x1?")

leia (x1)

escreva ("Qual o valor de x2?")

leia (x2)

escreva ("Qual o valor de x3?")

leia (x3)

escreva ("Qual o valor de y1?")

leia (y1)

escreva ("Qual o valor de y2?")

leia (y2)

escreva ("Qual o valor de y3?")

leia (y3)

d <- raizq((x3-x2-x1)^2)+((y3-y2-y1)^2)

escreva ("A distância entre os tres pontos e: ", d: 5:2)

Fimalgoritmo